n1 = int(input("Enter Number: "))
n2 = int(input("Enter Number: "))
n3 = int(input("Enter Number: "))
n4 = int(input("Enter Number: "))
n5 = int(input("Enter Number: "))
n6 = int(input("Enter Number: "))
n7 = int(input("Enter Number: "))
n8 = int(input("Enter Number: "))

a = set()
a.add(n1)
a.add(n2)
a.add(n3)
a.add(n4)
a.add(n5)
a.add(n6)
a.add(n7)
a.add(n8)

print(a)
